version: '2'
services:
  db:
    image: postgres:9.5.2
  web:
    build: .
    command: rackup --host 127.0.0.1 --port 4567 config.ru
    volumes:
      - .:/myapp
    ports:
      - "4567:4567"
    depends_on:
      - db
